#!/bin/bash
# /etc/init.d/sounder_script

### BEGIN INIT INFO
# Provides:          sounder_script
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a servo
### END INIT INFO


case "$1" in 
	start)
		echo "Starting sounder"
		/home/pi/workspace/run.sh
		;;
	stop)
		echo "Stopping sounder"
		killall sounder
		;;
	*)
		echo "Usage:
		/etc/init.d/sounder_script
		start|stop"
		exit
		1
		;;
esac

exit
0
